name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          BANNED_TOKEN: ${{ secrets.BANNED_TOKEN }}
          MOD_TOKEN: ${{ secrets.MOD_TOKEN }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
